language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-25.0.3
    - android-25

  licenses:
    - 'android-sdk-license-.+'

  cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.android/build-cache

script: ./gradlew check test